#!/bin/bash
# discover-env.sh — 用 avahi 被动发现节点, 写入 .env
# 不扫子网, 秒出结果, 适合 169.254/16 大网段

set -euo pipefail
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
ENV_FILE="${1:-$SCRIPT_DIR/.env}"

echo "=== 1. 检测网卡 ==="
ETH_IF=""
IB_IF=""

# 检测 IB 接口
mapfile -t PAIRS < <(ibdev2netdev 2>/dev/null | awk '/Up\)/ {print $1 " " $5}')
if [[ ${#PAIRS[@]} -eq 0 ]]; then
    echo "ERROR: 没有活跃的 IB 接口"
    exit 1
fi

declare -a IB_DEVS=()
declare -a NET_DEVS=()
for pair in "${PAIRS[@]}"; do
    ib=$(echo "$pair" | awk '{print $1}')
    net=$(echo "$pair" | awk '{print $2}' | tr -d '()')
    IB_DEVS+=("$ib")
    NET_DEVS+=("$net")
done

# 默认只取第一个 IB 设备 (多口 NCCL 可能不兼容)
IB_IF="${IB_DEVS[0]}"

# 选第一个有 IP 的作为 ETH_IF
for net in "${NET_DEVS[@]}"; do
    if ip addr show "$net" 2>/dev/null | grep -q "inet "; then
        ETH_IF="$net"
        break
    fi
done
[[ -z "$ETH_IF" ]] && { echo "ERROR: 没有有 IP 的网卡"; exit 1; }

echo "  ETH_IF=$ETH_IF"
echo "  IB_IF=$IB_IF"

# 本机 IP
LOCAL_IP=$(ip -o -f inet addr show "$ETH_IF" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1)
echo "  LOCAL_IP=$LOCAL_IP"

echo ""
echo "=== 2. avahi 被动发现节点 ==="

if ! command -v avahi-browse &>/dev/null; then
    echo "ERROR: avahi-browse 未安装 (apt install avahi-utils)"
    exit 1
fi

# 同 discover-sparks 的被动监听方式
avahi_output=$(avahi-browse -p -r -f -t _ssh._tcp 2>/dev/null)

TEMP_FILE=$(mktemp)
trap 'rm -f $TEMP_FILE' EXIT

# 只筛选 ETH_IF 所在接口的服务
echo "$avahi_output" | grep "$ETH_IF" > "$TEMP_FILE" 2>/dev/null || true

# 提取 IPv4 地址
grep "^=" "$TEMP_FILE" | grep "IPv4" | while IFS=';' read -r prefix interface protocol hostname_service description local fqdn ip_address port rest; do
    clean_ip=$(echo "$ip_address" | sed 's/;.*$//')
    if [[ $clean_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        echo "$clean_ip"
    fi
done | sort -u > "$TEMP_FILE.sorted"

mapfile -t FOUND_IPS < "$TEMP_FILE.sorted"

if [[ ${#FOUND_IPS[@]} -eq 0 ]]; then
    echo "WARNING: avahi 没发现其他节点, 只写入本机"
    ALL_NODES="$LOCAL_IP"
else
    echo "发现节点: ${FOUND_IPS[*]}"
    ALL_NODES="$LOCAL_IP"
    for ip in "${FOUND_IPS[@]}"; do
        [[ "$ip" != "$LOCAL_IP" ]] && ALL_NODES="$ALL_NODES,$ip"
    done
fi

echo ""
echo "=== 3. 写入 .env ==="
cat > "$ENV_FILE" << EOF
# Auto-generated by discover-env.sh
CLUSTER_NODES=$ALL_NODES
LOCAL_IP=$LOCAL_IP
ETH_IF=$ETH_IF
IB_IF=$IB_IF
EOF

echo "已写入 $ENV_FILE:"
cat "$ENV_FILE"
